server:
  port: 8088

midnightrpc:
  providers: http://localhost:8081,http://localhost:8082,http://localhost:8083
  zkServer: localhost:2182
  zkRoot: midnightrpc

app:
  id: app1
  namespace: public
  env: dev


logging:
  level:
    root: info