server:
  port: 8081

midnightrpc:
  zk:
    server: localhost:2181
    root: midnightrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: false
      unit: B002

