server:
  port: 8081

midnightrpc:
  zk:
    server: localhost:2181
    root: midnightrpc
  app:
    id: app1
    namespace: public
    env: dev
  provider:
    metas:
      dc: bj
      gray: true
      unit: B002
      tc: 20

midnightregistry:
  servers: http://localhost:8484

app:
  id: midnight
apollo:
  cacheDir: /opt/data/
  cluster: default
  meta: http://kimmking.cn:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: rpc-demo-provider.yaml
    eagerLoad:
      enabled: false

